package com.misensayosrs;
// Generated 20/09/2015 08:58:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * Establecimiento generated by hbm2java
 */

@javax.persistence.NamedQueries({
    @javax.persistence.NamedQuery(name = "establecimientoporprecio",
                query = "select i.establecimiento from Instrumento i join i.detalleInstrumento di where di.nombre in :nombrex and i.establecimiento.idEstablecimiento in "
                        +"("+"select e.idEstablecimiento from Establecimiento e join e.salas s where e.localidad=:localidadx order by s.precio DESC"+")"),
    @javax.persistence.NamedQuery(name = "establecimientoporcalificacion",                
                query = "select i.establecimiento, avg(c.calificacionEstablecimiento) as p from Instrumento i join i.ensayo e join e.calificacions c where i.establecimiento.idEstablecimiento in"
                        +"("+"select i.establecimiento.idEstablecimiento from Instrumento i join i.detalleInstrumento di where di.nombre in :nombrex and i.establecimiento.idEstablecimiento in "
                        +"("+"select e.idEstablecimiento from Establecimiento e where e.localidad = :localidadx"+")"+")"+"order by p DESC"),  
        
    @javax.persistence.NamedQuery(name = "horarioN",
                query = "select s.nombre, r.fecha , r.tiempo from Sala s join s.reservacions r where s.establecimiento.idEstablecimiento=0 and r.fecha<'Fecha'"),
    @javax.persistence.NamedQuery(name = "EstablecimientoInstru",
                query = "SELECT e.nombre, r.fecha, r.tiempo FROM Instrumento i JOIN i.establecimiento e JOIN e.salas s JOIN s.reservacions r JOIN i.detalleInstrumento di "
                        + "WHERE s.establecimiento.idEstablecimiento=:idEst AND r.fecha<:n AND i.idInstrumento=:idInst AND di.idDetalleInstrumento=0 "
                        + "AND 0=(SELECT COUNT(i.idInstrumento) FROM Instrumento i WHERE i.establecimiento=0 AND i.ensayo=null)")
})

@Entity
@Table(name="Establecimiento")
public class Establecimiento  implements java.io.Serializable {


     private int idEstablecimiento;
     private String nombre;
     private String nit;
     private String descripcion;
     private String direccion;
     private int horaInicio;
     private int horaCierre;
     private double multa;
     private String localidad;
     private String telefono;
     private Set<Instrumento> instrumentos = new HashSet(0);
     private Set<Sala> salas = new HashSet(0);

    public Establecimiento() {
    }

	
    public Establecimiento(int idEstablecimiento, String nombre, String nit, String direccion, int horaInicio, int horaCierre, double multa, String localidad, String telefono) {
        this.idEstablecimiento = idEstablecimiento;
        this.nombre = nombre;
        this.nit = nit;
        this.direccion = direccion;
        this.horaInicio = horaInicio;
        this.horaCierre = horaCierre;
        this.multa = multa;
        this.localidad = localidad;
        this.telefono = telefono;
    }
    public Establecimiento(int idEstablecimiento, String nombre, String nit, String descripcion, String direccion, int horaInicio, int horaCierre, double multa, String localidad, String telefono, Set<Instrumento> instrumentos, Set<Sala> salas) {
       this.idEstablecimiento = idEstablecimiento;
       this.nombre = nombre;
       this.nit = nit;
       this.descripcion = descripcion;
       this.direccion = direccion;
       this.horaInicio = horaInicio;
       this.horaCierre = horaCierre;
       this.multa = multa;
       this.localidad = localidad;
       this.telefono = telefono;
       this.instrumentos = instrumentos;
       this.salas = salas;
    }
   
     @Id 

    
    @Column(name="idEstablecimiento", unique=true, nullable=false)
    public int getIdEstablecimiento() {
        return this.idEstablecimiento;
    }
    
    public void setIdEstablecimiento(int idEstablecimiento) {
        this.idEstablecimiento = idEstablecimiento;
    }

    
    @Column(name="Nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="NIT", nullable=false, length=45)
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }

    
    @Column(name="Descripcion", length=1000)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="Direccion", nullable=false, length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="HoraInicio", nullable=false)
    public int getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(int horaInicio) {
        this.horaInicio = horaInicio;
    }

    
    @Column(name="HoraCierre", nullable=false)
    public int getHoraCierre() {
        return this.horaCierre;
    }
    
    public void setHoraCierre(int horaCierre) {
        this.horaCierre = horaCierre;
    }

    
    @Column(name="Multa", nullable=false, precision=22, scale=0)
    public double getMulta() {
        return this.multa;
    }
    
    public void setMulta(double multa) {
        this.multa = multa;
    }

    
    @Column(name="Localidad", nullable=false, length=18)
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }

    
    @Column(name="Telefono", nullable=false, length=45)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="establecimiento")
    public Set<Instrumento> getInstrumentos() {
        return this.instrumentos;
    }
    
    public void setInstrumentos(Set<Instrumento> instrumentos) {
        this.instrumentos = instrumentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="establecimiento")
    public Set<Sala> getSalas() {
        return this.salas;
    }
    
    public void setSalas(Set<Sala> salas) {
        this.salas = salas;
    }




}


